#ifndef FASTDYN_ARCH_ARM_V7M_H
#define FASTDYN_ARCH_ARM_V7M_H

#include <fastdyn/arch/arm32.h>

/* Cortex-M uses the ARM core-register layout; register 25 is xPSR. */
enum {
    VIRTUAL_ARM_V7M_R0 = VIRTUAL_ARM32_R0,
    VIRTUAL_ARM_V7M_R1 = VIRTUAL_ARM32_R1,
    VIRTUAL_ARM_V7M_R2 = VIRTUAL_ARM32_R2,
    VIRTUAL_ARM_V7M_R3 = VIRTUAL_ARM32_R3,
    VIRTUAL_ARM_V7M_R4 = VIRTUAL_ARM32_R4,
    VIRTUAL_ARM_V7M_R5 = VIRTUAL_ARM32_R5,
    VIRTUAL_ARM_V7M_R6 = VIRTUAL_ARM32_R6,
    VIRTUAL_ARM_V7M_R7 = VIRTUAL_ARM32_R7,
    VIRTUAL_ARM_V7M_R8 = VIRTUAL_ARM32_R8,
    VIRTUAL_ARM_V7M_R9 = VIRTUAL_ARM32_R9,
    VIRTUAL_ARM_V7M_R10 = VIRTUAL_ARM32_R10,
    VIRTUAL_ARM_V7M_R11 = VIRTUAL_ARM32_R11,
    VIRTUAL_ARM_V7M_R12 = VIRTUAL_ARM32_R12,
    VIRTUAL_ARM_V7M_SP = VIRTUAL_ARM32_SP,
    VIRTUAL_ARM_V7M_LR = VIRTUAL_ARM32_LR,
    VIRTUAL_ARM_V7M_PC = VIRTUAL_ARM32_PC,
    VIRTUAL_ARM_V7M_XPSR = 25,
};

#endif
