[package]
name = "baby_fuzzer"
version = "0.14.1"
authors = [
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
]
edition = "2021"

[features]
default = ["std", "gazebo"]
tui = []
std = []
gazebo = ["dep:gz-msgs", "dep:gz-transport", "dep:protobuf"]

[[bin]]
name = "trace_recorder"
path = "src/bin/trace_recorder/main.rs"
required-features = ["gazebo"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
banquo = { path = "../../../../banquo/banquo" }
banquo-parser = { path = "../../../../banquo/banquo-parser" }
csv = "1.4.0"
env_logger = "0.11.7"
gz-msgs = { version = "0.9.0", optional = true }
gz-transport = { version = "0.9.0", optional = true }

# libafl = { path = "../../../../LibAFL-0.15.4/crates/libafl", features = ["tui_monitor"] }
# libafl_bolts = { path = "../../../../LibAFL-0.15.4/crates/libafl_bolts" }
libafl = { version = "0.15.4", features = ["tui_monitor"] }
libafl_bolts = "0.15.4"

log = { version = "0.4.22", features = ["release_max_level_info"] }
ordered-float = "5.1.0"
protobuf = { version = "3.7.2", optional = true }
scirs2-core = "0.1.1"
scirs2-optimize = "0.1.1"
serde = "1.0.228"
serde_json = "1.0.149"
reqwest = { version = "0.11", features = ["json", "blocking"] }
