"""Generic RTOS hook construction support for the introspection host code."""

from abc import ABC, abstractmethod
import capstone
from elftools.elf.elffile import ELFFile
from fastdyn.machine import VirtualInstruction

class RTOSIntrospector(ABC):
    # This dictionary acts as our internal Plugin Registry
    _registry = {}

    def __init_subclass__(cls, rtos_name: str | None = None, **kwargs):
        super().__init_subclass__(**kwargs)
        # Abstract/helper subclasses deliberately omit a name; concrete
        # implementations register themselves under the detected RTOS name.
        if rtos_name is not None:
            cls._registry[rtos_name] = cls

    def __init__(self, cpu_obj, symbols, binary, *, architecture="", machine="", cpu=""):
        # cpu_obj is retained as a compatibility parameter for external
        # introspectors. The frontend now collects generated rules from this
        # object instead of mutating a CPU/frontend object directly.
        self.cpu = cpu_obj
        self.symbols = symbols
        self.binary = binary
        self.architecture = architecture
        self.machine = machine
        self.cpu_model = cpu
        self.virtuals: list[VirtualInstruction] = []

    @abstractmethod
    def setup_hooks(self):
        """Must be implemented by subclasses to wire up the QEMU hooks."""
        pass

    def register_prologue_hook(self, sym_name):
        hook_sym = self.symbols.get(sym_name)
        found_sym_with_elf = False
        hook_sym_addr = None
        if hook_sym is None:
            with open(self.binary, "rb") as f:
                elf = ELFFile(f)
                symtab = elf.get_section_by_name(".symtab")
                if not symtab:
                    print("No symbol table")
                    return False
                for sym in symtab.iter_symbols():
                    if sym.name == sym_name:
                        hook_sym_addr = sym.entry.st_value
                        # handle thumb bit for arm binaries
                        if hook_sym_addr & 1:
                            hook_sym_addr &= ~1
                        found_sym_with_elf = True
            if not found_sym_with_elf:
                print(f"[hook] Symbol '{sym_name}' not found")
                return False
        hook_sym_addr = hook_sym.address if hook_sym else hook_sym_addr
        # DWARF uses the Thumb-bit-marked function address on Cortex-M while
        # QEMU's instruction callback keys rules by the aligned instruction
        # address. ELF-table fallback above already does this; do it for
        # DWARF-provided function symbols too.
        if isinstance(hook_sym_addr, int) and hook_sym_addr & 1:
            hook_sym_addr &= ~1
        # DWARF can retain declarations for inline or macro-only APIs with a
        # zero address. They are not executable hook locations; emitting them
        # creates conflicting virtual rules at the reset-vector address.
        if not isinstance(hook_sym_addr, int) or hook_sym_addr == 0:
            print(f"[hook] Symbol '{sym_name}' has no executable address")
            return False
        cb = VirtualInstruction(
                    at=hook_sym_addr,
                    instruction=f"{sym_name}_Hook",
                    args=[]
                )
        self.virtuals.append(cb)
        print(f"[hook] Successfully registered prologue hook for '{sym_name}' at 0x{hook_sym_addr:x}")
        return True

    def register_epilogue_hook(self, sym_name):
        epi_name = sym_name + "_epi"
        hook_sym = self.symbols.get(epi_name)
        if hook_sym is None:
            addresses = self._elf_return_addresses(sym_name)
            if not addresses:
                print(f"[hook] Symbol '{sym_name}' not found")
                return False
        else:
            addresses = hook_sym.address

        if isinstance(addresses, int):
            addresses = [addresses]

        # A function can have multiple returns, each of which needs a rule.
        for hook_sym_addr in addresses:
            if hook_sym_addr & 1:
                hook_sym_addr &= ~1
            cb = VirtualInstruction(
                        at=hook_sym_addr,
                        instruction=f"{epi_name}_Hook",
                        args=[]
                    )
            self.virtuals.append(cb)

        print(f"[hook] Successfully registered epilogue hook for '{sym_name}' at {len(addresses)} return site(s)")
        return True

    def _elf_return_addresses(self, sym_name):
        """Recover ARM Thumb return sites when DWARF lacks an epilogue DIE.

        ELF symbol-table fallback is common in release-like RTOS builds.  It
        supplies a function address and size but not the synthetic
        ``<name>_epi`` symbol generated by :class:`DwarfProvider`; scanning
        the exact function range closes that gap without broad disassembly.
        """
        symbol = self.symbols.get(sym_name)
        if symbol is not None and isinstance(symbol.address, int) and symbol.size:
            start = symbol.address & ~1
            size = int(symbol.size)
        else:
            # Some useful assembly-only routines (notably Zephyr's Cortex-M
            # PendSV handler) have an ELF symbol but no DWARF DIE. Resolve
            # their exact range from .symtab before scanning it.
            start = None
            size = 0
            try:
                with open(self.binary, "rb") as stream:
                    symtab = ELFFile(stream).get_section_by_name(".symtab")
                    if symtab:
                        symbol_section = None
                        for entry in symtab.iter_symbols():
                            if entry.name == sym_name:
                                start = int(entry.entry.st_value) & ~1
                                size = int(entry.entry.st_size)
                                symbol_section = entry.entry.st_shndx
                                break
                        # GNU assembler frequently writes st_size=0 for a
                        # global label. Bound it by the next function in the
                        # same section so return scanning cannot leak into
                        # unrelated routines.
                        if start is not None and size == 0:
                            following = [
                                (int(entry.entry.st_value) & ~1)
                                for entry in symtab.iter_symbols()
                                if entry.entry.st_shndx == symbol_section
                                and entry.entry.st_info.type == "STT_FUNC"
                                and (int(entry.entry.st_value) & ~1) > start
                            ]
                            if following:
                                size = min(following) - start
            except OSError:
                return []
            if start is None:
                return []
        try:
            with open(self.binary, "rb") as stream:
                elf = ELFFile(stream)
                code = b""
                for segment in elf.iter_segments():
                    if segment["p_type"] != "PT_LOAD":
                        continue
                    segment_start = int(segment["p_vaddr"])
                    segment_end = segment_start + int(segment["p_filesz"])
                    if segment_start <= start < segment_end:
                        offset = int(segment["p_offset"]) + (start - segment_start)
                        stream.seek(offset)
                        # Assembly labels often have a zero ELF st_size. A
                        # bounded scan still finds their first return without
                        # turning this into a broad binary disassembly.
                        scan_size = size if size > 0 else 512
                        code = stream.read(min(scan_size, segment_end - start))
                        break
        except OSError:
            return []

        if not code:
            return []
        disassembler = capstone.Cs(
            capstone.CS_ARCH_ARM, capstone.CS_MODE_THUMB | capstone.CS_MODE_MCLASS
        )
        returns = []
        for instruction in disassembler.disasm(code, start):
            if ((instruction.mnemonic == "bx" and "lr" in instruction.op_str)
                    or (instruction.mnemonic.startswith("pop") and "pc" in instruction.op_str)
                    # Cortex-M compiler prologues commonly return through
                    # ``ldmia sp!, {..., pc}``, which Capstone does not spell
                    # as ``pop``.
                    or (instruction.mnemonic.startswith("ldm") and "pc" in instruction.op_str)):
                returns.append(instruction.address)
        return returns

    @classmethod
    def create(
        cls, rtos_name: str, cpu_obj, symbols, binary, *, architecture="", machine="", cpu=""
    ) -> 'RTOSIntrospector':
        """Factory method to instantiate the correct introspector plugin."""
        introspector_class = cls._registry.get(rtos_name)
        if not introspector_class:
            raise NotImplementedError(f"No introspector plugin registered for: {rtos_name}")

        return introspector_class(
            cpu_obj, symbols, binary,
            architecture=architecture, machine=machine, cpu=cpu,
        )
