# ==============================================================================
#                              Memory Configuration
# ==============================================================================
[Memory]

[Memory.main]   # required: goes to -machine ... memory-backend=<id>
id = "ram0"
base_address = "0x20000000"
memory_size  = "512M"
memory_type  = "SRAM"
backend      = "file"          # file | ram | memfd
memory_file  = "/dev/shm/my_m4_ram3"
share        = true
prealloc     = false

[[Memory.ram1]]   # optional banks: go to -global cortexm-soc.ram_backendN / ram_baseaddrN
id = "ram1"
index = 1
base_address = "0x30000000"
memory_size  = "512K"
memory_type  = "SRAM"
backend      = "file"
memory_file  = "/dev/shm/my_m4_ram"
share        = true
prealloc     = false

# ==============================================================================
#                                CPU Configuration
# ==============================================================================
[Machine]
platform = "STM32F429"
# --- Debugging, Control, and Logging ---
qemu_path = "qemu/build/qemu-system-arm"
enable_gdb = true
stop_on_start = true
launch_gdb = false
monitor_port = 5555
qmp_socket = "/tmp/qmp.sock"
log_file = "qemu.log"
log_options = "in_asm,op"
semihosting = true
semihosting_config = "enable=on,target=native"
coverage=false
finline='None'
print_command = true          #set to true if you want to print the final qemu on the terminal [Useful for debugging]

[CPU]
[[CPU.cpu0]]
# --- Core Emulation & Plugin Settings ---
arch = "arm"
machine = "cortexm"
cpu = "cortex-m3"
plugin_library = "build/libfastdyn.so"
monitor_elf = "../ws/monitor.elf" # The VMM-like monitor that runs with the target
binary = "tests/sample_binaries/RTOS/RTOSDemo.axf"
init_nsvtor = "0x08000000"
twintrace = "None" #options are record, replay or None
hardware_trace = 'hardware_log/io.log'   #useful in cases like replay to generate the replay binary
existing_config_path  = false #'/path/to/dir containing virtuals.txt and modifiers.txt' add your existing virtuals.txt here, will traverse through to find the virtuals.txt and modifiers.txt

[CPU.cpu0.plugins.introspection]
enabled = true


# --- Embedded CPU Behavior Configurations ---
logger_content = """
# --- Plugin Logger Configuration ---
# level = DEBUG
# output = stderr
"""

# ==============================================================================
#                              Device Configuration
# ==============================================================================

# --- Model-Specific Configurations ---
# Define the global arguments for each type of plugin device model here.

[Device.Models.elder]
    # The libhw backend is a global argument for the elder model.

[Device.Models.passthrough]
    backend = "stlink"

[Device.Models.classic]
    # The classic model has no global arguments.

[Device.Models.twintrace]
    backend = "stlink"
    # The classic model has no global arguments.

[Device.Models.unhandled]
    # This model explicitly marks memory as unhandled.

# --- Peripheral Definitions ---
[Device.remaining_space]
    ranges = [["0x40000000", "0x400107FF"],["0x40010C00", "0x40010FFF"], ["0x40011400", "0xE0000000"], ["0xE0000000", "0xEFFFFFFF"]]
    irq = [['1','100']]
    description = "Memory regions that will handled by passthrough and are not of interest for the modeling."

    [[Device.remaining_space.handlers]]
        model = "classic"
        enabled = false
