"""Read-only web observer for a world-backed FastDyn run.

world_model ships an observer that plots a trace CSV alongside the model
metadata generated from a world TOML. It is deliberately read-only: it reads
artifacts and cannot control the world, which is exactly right here, because
the guest owns when physics advances.

FastDyn's runtime writes the trace, but not the metadata the observer needs.
This module derives a world TOML from the plugin's configuration, runs
world_model's own generator to produce `world_manifest.json` and
`ui_config.json` from it, and serves them. Generating rather than hand-writing
those files keeps world_model's artifact format in world_model.
"""

from __future__ import annotations

import importlib.util
import os
import subprocess
import sys
import threading
from http.server import ThreadingHTTPServer
from pathlib import Path

from fastdyn.virtual_preprocessing import VirtualPreparationError

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8770


def _toml_string(value: str) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_world_toml(
    destination: Path,
    *,
    models: dict,
    endpoints: dict,
    connections: dict,
    step_ns: int,
    stop_ns: int,
    trace_output: Path,
    trace_variables: list[str],
    host: str,
    port: int,
    open_browser: bool,
) -> Path:
    """Render a world TOML describing this run, for the observer's metadata.

    `trace_output` is the path FastDyn's runtime actually writes, so the
    generated ui_config points the observer at the live trace.
    """
    lines = [
        "# Generated by FastDyn from [CPU.cpu0.plugins.world]; do not edit.",
        "# Describes the running world so the observer can label and plot it.",
        "",
        "[World]",
        "start = 0",
        f"stop = {stop_ns}",
        f"step = {step_ns}",
        'time_unit = "ns"',
        "",
    ]

    inputs = {a: s for a, s in endpoints.items() if s["direction"] == "in"}
    outputs = {a: s for a, s in endpoints.items() if s["direction"] == "out"}
    if inputs:
        lines.append("[World.Inputs]")
        lines += [f"{alias} = {_toml_string(spec['target'])}" for alias, spec in inputs.items()]
        lines.append("")
    if outputs:
        lines.append("[World.Outputs]")
        lines += [f"{alias} = {_toml_string(spec['target'])}" for alias, spec in outputs.items()]
        lines.append("")

    for name, model in models.items():
        lines.append(f"[Models.{name}]")
        lines.append(f"path = {_toml_string(model['path'])}")
        lines.append("")
        parameters = model.get("parameters") or {}
        if parameters:
            lines.append(f"[Models.{name}.Parameters]")
            lines += [f"{key} = {float(value)!r}" for key, value in parameters.items()]
            lines.append("")

    if connections:
        lines.append("[Connections]")
        lines += [f"{_toml_string(src)} = {_toml_string(dst)}" for src, dst in connections.items()]
        lines.append("")

    lines.append("[Trace]")
    lines.append(f"output = {_toml_string(str(trace_output))}")
    if trace_variables:
        rendered = ", ".join(_toml_string(v) for v in trace_variables)
        lines.append(f"variables = [{rendered}]")
    lines.append("")
    lines.append("[Frontend]")
    lines.append("enabled = true")
    lines.append(f"host = {_toml_string(host)}")
    lines.append(f"port = {port}")
    # FastDyn owns the observer's lifetime, so the generator must not start it.
    lines.append("launch_on_generate = false")
    lines.append(f"open_browser = {'true' if open_browser else 'false'}")

    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return destination


def generate_artifacts(world_root: Path, world_toml: Path, out_dir: Path) -> Path:
    """Run world_model's generator to produce the observer's metadata."""
    generator = world_root / "tools" / "wm.py"
    if not generator.is_file():
        raise VirtualPreparationError(
            f"world observer needs world_model's generator at {generator}. "
            "Run: git submodule update --init tools/world"
        )
    environment = dict(os.environ, WM_NO_FRONTEND_LAUNCH="1")
    result = subprocess.run(
        [sys.executable, str(generator), "generate", str(world_toml), "--out", str(out_dir)],
        capture_output=True, text=True, env=environment, cwd=str(world_root),
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip().splitlines()
        raise VirtualPreparationError(
            "world observer could not generate its metadata: "
            + (detail[-1] if detail else f"wm.py exited {result.returncode}")
        )
    manifest = out_dir / "world_manifest.json"
    if not manifest.is_file():
        raise VirtualPreparationError(
            f"world observer metadata was not produced at {manifest}"
        )
    return manifest


def start_observer(world_root: Path, artifacts: Path) -> tuple[ThreadingHTTPServer, str]:
    """Serve world_model's observer over the generated artifacts.

    world_model's own run_server() blocks forever, so its request handler is
    reused here behind a server FastDyn can shut down. Host, port and
    open_browser come from the generated manifest, as world_model intends.
    """
    module_path = world_root / "tools" / "wm_server.py"
    spec = importlib.util.spec_from_file_location("fastdyn_wm_server", module_path)
    if spec is None or spec.loader is None:
        raise VirtualPreparationError(f"world observer cannot load {module_path}")
    wm_server = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(wm_server)

    try:
        observer = wm_server.RunObserver(artifacts)
    except (OSError, ValueError) as exc:
        raise VirtualPreparationError(f"world observer cannot read {artifacts}: {exc}") from exc

    frontend = observer.manifest.get("frontend") or {}
    handler = type(
        "FastDynWorldObserverHandler",
        (wm_server.ObserverHandler,),
        {"observer": observer, "log_message": lambda *_args: None},
    )
    try:
        server = ThreadingHTTPServer(
            (frontend.get("host", DEFAULT_HOST), int(frontend.get("port", DEFAULT_PORT))),
            handler,
        )
    except OSError as exc:
        raise VirtualPreparationError(
            f"world observer could not bind "
            f"{frontend.get('host', DEFAULT_HOST)}:{frontend.get('port', DEFAULT_PORT)}: {exc}"
        ) from exc

    host, port = server.server_address[:2]
    threading.Thread(target=server.serve_forever, daemon=True).start()
    url = f"http://{host}:{port}"
    if frontend.get("open_browser", False):
        import webbrowser
        webbrowser.open(url)
    return server, url
